### ISSUE TITLE
Getting "Too many requests" error code 429 repeatedly

### ISSUE THREAD

**Issue by dSwagler** [RMCob/homebridge-wyze-connected-home-op#21] opened 2022-01-23 17:40 UTC
I have installed this plugin yesterday and since have been receiving too many requests errors with code 429. I have verified the configuration was corrected, however, I do not know if I have a two-factor token. 

Any help with the error would be appreciated.

PS - this is a brand new RasPi 4B with 32GB card running a fresh install of HOOBS and the plugin is on its own bridge. Only other plugin is Tplink Smarthome Bridge which is running fine.

**Comment by dadbot6000** [comment] 2022-01-25 02:24
I'm having this issue as well. Any help would be appreciated. :)

**Comment by RMCob** [comment] 2022-01-25 17:34
This is a duplicate of Issue #14 & Issue #10. Please see them for details....

**Closed as completed by RMCob** 2022-01-25 17:34 UTC
