### ISSUE TITLE
Devices lose room assignments on restart of Homebridge

### ISSUE THREAD

**Issue by dlewanda** [RMCob/homebridge-wyze-connected-home-op#24] opened 2022-02-06 14:03 UTC
For the life of me, I can't seem to figure out how to keep the Wyze devices assigned to rooms across unplanned restarts (eg. power outages, hard reboots of my Raspberry Pi). Has anyone else seen this? Is there a fix that won't require a code change? Thanks in advance for any guidance!

**Comment by RMCob** [comment] 2022-02-24 21:23
This is a duplicate of #22 .

**Closed as completed by RMCob** 2022-02-24 21:23 UTC
