### ISSUE TITLE
429 error

### ISSUE THREAD

**Issue by sisuwest** [RMCob/homebridge-wyze-connected-home-op#14] opened 2021-12-23 15:03 UTC
Last night I started to get 429 status code errors. It won’t update the devices or even allow me to use them. I thought it might be 2fa, so I turned it off and it still persists. I then thought it was your beta 0.5.9, so I downgraded to 0.5.8. Still nothing. Any ideas?

**Comment by RMCob** [comment] 2021-12-26 17:09
Could be a problem on Wyze's end. Is it still happening?

**Comment by sisuwest** [comment] 2021-12-26 17:33
Yes. Although everything works within Apple Home, just not on Hoobs.
<img width="1105" alt="Screen Shot 2021-12-26 at 10 32 11 AM" src="https://user-images.githubusercontent.com/65087400/147415766-ab9723bc-36d1-4163-a0be-841bc5ab5efe.png">

**Comment by RMCob** [comment] 2021-12-26 20:00
This is a duplicate of Issue #10. 

This plugin was written for Homebridge, not Hoobs. I have no idea what the Hoobs infrastructure may or may not be doing behind the scenes. You can always resolve the problem by opening a terminal window and creating the missing directory manually. ex: $ sudo mkdir /var/lib/hoobs/wyzeconnectedhomeopbridge/persist; sudo chmod 777 /var/lib/hoobs/wyzeconnectedhomeopbridge/persist

**Closed as completed** 2022-01-12 16:47 UTC
