### ISSUE TITLE
How about adding support for the Wyze Wall Switch?

### ISSUE THREAD

**Issue by SteveQ2** [RMCob/homebridge-wyze-connected-home-op#26] opened 2022-02-24 19:45 UTC
The Wyze Wall switch is an extremely useful addition to there product line. The double tap and triple tap feature would be an excellent way to control non Wyze accessories via HomeBridge.

**Comment by RMCob** [comment] 2022-02-24 21:18
@SteveQ2 This is a duplicate of issue #13. As I stated there, I do not have and cannot install a Wyze Switch because my house is 51 years old and doesn't have the neutral wires in the switch boxes. Not having one installed locally makes it impossible to develop software for it. And the multi-tap features would not be exposed to Homebridge anyway. The detection of multi-taps is a hardware feature. Not sure how that event would be visible to the plugin. Sorry.

**Closed as completed by RMCob** 2022-02-24 21:18 UTC

**Comment by sisuwest** [comment] 2022-04-22 18:15
Hey there! Just checking in on this one. I'm only interested in the on/off of the switch and not multi taps. I believe I sent you some logs previously that would help, but I don't recall what came of it.
